# 010. PyTorch basic

- GPU check 부분이 있으므로 Google Colab에서 실행

In [8]:
import torch
import numpy as np
import matplotlib.pyplot as plt

device = "cuda:0" if torch.accelerator.is_available() else "cpu"
device

'cuda:0'

In [9]:
torch.accelerator.is_available()

True

In [10]:
torch.__version__

'2.10.0+cu128'

## Tensor Data Types

### torch.tensor 함수

`tensor(data, dtype=None, device=None, requires_grad=False) -> Tensor`

     data (array_like): list, tuple, numpy ndarray, scalar, and other types.
     dtype :  `None`인 경우 `data`에서 데이터 유형을 유추합니다.  
     device : `cpu`, `cuda`  
     require_grad(bool, optional): autograd가 작업을 기록해야 하는 경우

Float torch tensor 생성

In [11]:
# numpy array 생성
a = np.ones((2, 3), dtype="float32")
# tensor 생성
b = torch.tensor(a)
# dtype
print(a.dtype, '\t', b.dtype)

float32 	 torch.float32


Integer tensor 생성

In [12]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32)
x

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [13]:
# gpu tensor
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32, device=device)
x

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0', dtype=torch.int32)

## 1D Tensor Operation

In [14]:
a = torch.tensor([1, 2, 3, 4, 5])

a[0], a[-1]

(tensor(1), tensor(5))

In [15]:
a.size()

torch.Size([5])

In [16]:
a.ndimension()

1

In [17]:
a.view(5, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5]])

### Tensor Type 변환

- cpu <--> gpu

In [18]:
# cpu tensor
a = a.to(dtype=torch.float32)
a

tensor([1., 2., 3., 4., 5.])

In [19]:
# gpu tensor
b = a.to(device)
b

tensor([1., 2., 3., 4., 5.], device='cuda:0')

In [20]:
# cpu tensor
d = b.to("cpu")
d

tensor([1., 2., 3., 4., 5.])

In [68]:
print(b.device)
print(d.device)

cuda:0
cpu


### Tensor 생성

- 무작위로 초기화된 행렬 생성 (uniform distribution)

In [21]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4593, 0.5954, 0.9099],
        [0.7237, 0.7797, 0.4482],
        [0.9943, 0.4448, 0.9322],
        [0.4683, 0.7527, 0.6190],
        [0.4642, 0.2653, 0.0522]])


- dtype이 long이고 0으로 채워진 행렬 생성

In [22]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)
print(x.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.int64


- python list로 부터 tensor 생성

In [23]:
# python list로부터 tensor 생성
a = torch.tensor([7, 4, 3, 2, 6])
a.dtype

torch.int64

In [65]:
x_ones = torch.ones_like(a)
x_rand = torch.rand_like(a, dtype=torch.float)

x_ones, x_rand

(tensor([1., 1., 1., 1., 1.]),
 tensor([0.6762, 0.9420, 0.8710, 0.7352, 0.5946]))

## Tensor 의 shape & dimension (rank)

In [24]:
a = torch.tensor([0, 1, 2, 3, 4])
# size() 와 shape 은 alias --> 권장 방식
a.shape
a.size()

torch.Size([5])

In [25]:
a.ndimension()

1

## reshape
- torch.view : original tensor의 memory 공유 (contiguity 제한)
- torch.reshape: contiguity 제한 없음. 필요에 따라 new tensor 생성. numpy 와 유사한 operation을 위해 기능 제공

In [26]:
print(a)
print(a.view(5, 1))
print(a.reshape(5, 1))

tensor([0, 1, 2, 3, 4])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])


In [27]:
# 4x4 크기의 랜덤한 텐서 생성
x = torch.randn(4, 4)

# view: original tensor의 memory 공유 (contiguity 제한)
y = x.view(16)
# reshape: contiguity 제한 없음, -1은 나머지 차원의 크기를 자동 계산
z = x.reshape(-1, 8)

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [28]:
# transpose 후에는 contiguity가 깨질 수 있음
# reshape은 contiguity 제한이 없지만, view는 제한이 있음
x = torch.randn(4, 4)
x.transpose(0, 1).reshape(-1, 8)  # reshape은 가능
# x.transpose(0, 1).view(-1, 8)   # view는 에러 발생 가능

tensor([[-1.3996,  1.0438,  1.7867, -0.9003, -0.9851,  0.8064, -0.3797,  1.4224],
        [ 1.9934, -0.2222, -0.2837,  1.6302, -0.9443,  0.1476, -1.5403, -0.6899]])

## numpy 와 tensor 간의 호환성

- memory 를 공유하므로 하나를 수정하면 나머지에 모두 반영  

In [29]:
numpy_array = np.array([0.0, 1.0, 2.0, 3.0, 4.0, 5.0])       # numpy array
torch_tensor = torch.from_numpy(numpy_array)               # torch tensor
torch_tensor

tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)

In [30]:
back_to_numpy = torch_tensor.numpy()           # numpy array
back_to_numpy

array([0., 1., 2., 3., 4., 5.])

In [31]:
numpy_array, torch_tensor, back_to_numpy

(array([0., 1., 2., 3., 4., 5.]),
 tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64),
 array([0., 1., 2., 3., 4., 5.]))

In [32]:
back_to_numpy[0] = 100

numpy_array, torch_tensor, back_to_numpy

(array([100.,   1.,   2.,   3.,   4.,   5.]),
 tensor([100.,   1.,   2.,   3.,   4.,   5.], dtype=torch.float64),
 array([100.,   1.,   2.,   3.,   4.,   5.]))

## Scalar value

- 만약 tensor에 하나의 값만 존재한다면, ``.item()`` method를 사용하여 숫자 값을 얻을 수 있습니다.  

In [33]:
# tensor에 하나의 값만 존재하는 경우 .item()으로 숫자 값 얻기
x = torch.randn(1)
x.item()

a = torch.tensor([5., 3., 4., 1.])
a[0].item()

5.0

## Tensor 의 indexing & slicing

- Python 의 indexing & slicing 과 동일

In [34]:
c = torch.tensor([20, 1, 2, 3, 4])
c[0] = 100
c[4] = 0
c, c.dtype

(tensor([100,   1,   2,   3,   0]), torch.int64)

In [35]:
d = c[1:4]
d

tensor([1, 2, 3])

In [36]:
c[3:5] = torch.tensor([300.0, 400.0])
c

tensor([100,   1,   2, 300, 400])

## Basic Operations - numpy 와 동일

In [37]:
# element-wise 덧셈, 뺄셈
u = torch.tensor([1.0, 0.0])
v = torch.tensor([0.0, 1.0])
z = u + v
z

tensor([1., 1.])

In [38]:
z = u - v
z

tensor([ 1., -1.])

In [39]:
# element-wise 곱셈
u = torch.tensor([1, 2])
v = torch.tensor([3, 2])
z = u * v
z

tensor([3, 4])

In [40]:
# 스칼라 곱
y = torch.tensor([1, 2])
z = 2 * y
z

tensor([2, 4])

In [41]:
# dot product
u = torch.tensor([1, 2])
v = torch.tensor([3, 1])
result = torch.dot(u, v)
result

tensor(5)

## 기타

In [42]:
# broadcasting
u = torch.tensor([1, 2, 3, -1])
z = u + 1
z

tensor([2, 3, 4, 0])

In [43]:
# mean, max, Standard Deviation
a = torch.tensor([1, -2, 3, 4, 5], dtype=torch.float32)

a.mean(), a.max(), a.std()

(tensor(2.2000), tensor(5.), tensor(2.7749))

## torch.linspace 와 torch.arange

In [44]:
# linspace: 시작값과 끝값 사이를 균등하게 나눔
torch.linspace(-2, 2, 5)

tensor([-2., -1.,  0.,  1.,  2.])

In [45]:
# arange: 시작값부터 끝값 전까지 step 간격으로 생성
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

## 2D Tensor Operation

In [46]:
_2d_tensor = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33], [41, 42, 43]])
_2d_tensor

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33],
        [41, 42, 43]])

- ndimension  
- shape  
- size()  
- numel (number of elements)

In [47]:
print(_2d_tensor)
print(_2d_tensor.ndimension())
print(_2d_tensor.shape)
print(_2d_tensor.size())
print(_2d_tensor.numel())

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33],
        [41, 42, 43]])
2
torch.Size([4, 3])
torch.Size([4, 3])
12


## matrix 간의 연산

In [48]:
x = torch.tensor([[1, 0], [0, 1]])
y = torch.tensor([[2, 1], [1, 2]])
print(x)
print(y)

tensor([[1, 0],
        [0, 1]])
tensor([[2, 1],
        [1, 2]])


- element-wise 연산

In [49]:
x * y

tensor([[2, 0],
        [0, 2]])

## matrix multiplication

In [50]:
x = torch.tensor([[0, 1, 1], [1, 0, 1]])
y = torch.tensor([[1, 1], [1, 1], [-1, 1]])

print(x)
print(y)

tensor([[0, 1, 1],
        [1, 0, 1]])
tensor([[ 1,  1],
        [ 1,  1],
        [-1,  1]])


In [51]:
torch.matmul(x, y)

tensor([[0, 2],
        [0, 2]])

### Concatenation

- default - first axis(row-wise)로 concatenate
- column-wise로 concatenate 하려면 axis=1 로 지정

In [53]:
x_1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
x_2 = torch.tensor([[7, 8, 9], [10, 11, 12]])
print(x_1)
print(x_2)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])


In [54]:
torch.cat([x_1, x_2])

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [55]:
torch.cat([x_1, x_2], dim=1)

tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])

### torch.sum, torch.max, torch.min, torch.argmax, torch.argmin

- torch.sum(input, dim, keepdim=False, dtype=None) → Tensor  
주어진 차원 dim에서 입력 텐서의 각 행의 합(max, min)을 반환합니다.

- dim 을 지정한 경우, 지정된 dim을 축소하는 것입니다. 따라서 dim 0(행)을 접으면 하나의 행이 됩니다(열 단위로 합산).

In [56]:
x = torch.tensor([
     [1, 2, 3],
     [4, 5, 6]
   ])
x.shape

torch.Size([2, 3])

In [57]:
torch.sum(x)

tensor(21)

In [58]:
torch.sum(x, dim=0)

tensor([5, 7, 9])

In [59]:
torch.sum(x, dim=1)

tensor([ 6, 15])

In [60]:
torch.max(x, dim=0), torch.min(x, dim=0)

(torch.return_types.max(
 values=tensor([4, 5, 6]),
 indices=tensor([1, 1, 1])),
 torch.return_types.min(
 values=tensor([1, 2, 3]),
 indices=tensor([0, 0, 0])))

In [61]:
torch.max(x, dim=1), torch.min(x, dim=1)

(torch.return_types.max(
 values=tensor([3, 6]),
 indices=tensor([2, 2])),
 torch.return_types.min(
 values=tensor([1, 4]),
 indices=tensor([0, 0])))

In [62]:
torch.argmax(x), torch.argmin(x)

(tensor(5), tensor(0))

In [63]:
torch.argmax(x, dim=0), torch.argmin(x, dim=0)

(tensor([1, 1, 1]), tensor([0, 0, 0]))

In [64]:
torch.argmax(x, dim=1), torch.argmin(x, dim=1)

(tensor([2, 2]), tensor([0, 0]))